[build]
  publish = "."

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/operations"
  to = "/operations.html"
  status = 200

[[redirects]]
  from = "/gallery"
  to = "/gallery.html"
  status = 200

[[redirects]]
  from = "/locate"
  to = "/locate.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/teams"
  to = "/teams.html"
  status = 200

[[redirects]]
  from = "/team"
  to = "/teams.html"
  status = 301
